<a href="https://colab.research.google.com/github/DhruvMazumdar1110/Weather-Data-Preprocessing/blob/main/Weather_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

IMPORTING THE LIBRARIES

In [6]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

IMPORTING THE DATASET

In [7]:
dataset = pd.read_csv('weather_data.csv')
X= dataset.iloc[: , [0,1,3,4,5] ].values
y= dataset.iloc[: , 2].values

In [8]:
print(X)

[['San Diego' '2024-01-14 21:12:46' 41.19575356694448 4.02011871570867
  8.233540246873023]
 ['San Diego' '2024-05-17 15:22:10' 58.31910739552024 9.111623448229375
  27.71516125689249]
 ['San Diego' '2024-05-11 09:30:59' 38.82017526915946 4.607511377146035
  28.732951288236187]
 ...
 ['San Jose' '2024-03-14 18:09:08' 81.31372480473425 2.161627975805372
  4.538363818725676]
 ['San Diego' '2024-02-08 21:12:09' 36.20267562952184 3.749677285096752
  9.298500900336268]
 ['New York' '2024-04-14 20:46:30' 80.68813773360876 8.539702382693964
  29.0]]

In [9]:
print(y)

[10.68300109  8.73413978 11.63243631 ... 34.0458259  37.54190568
 12.72276518]

HANDLING MISSING DATA

In [10]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 2:])
X[:, 2:] = imputer.transform(X[:, 2:])
print(X)

[['San Diego' '2024-01-14 21:12:46' 41.19575356694448 4.02011871570867
  8.233540246873023]
 ['San Diego' '2024-05-17 15:22:10' 58.31910739552024 9.111623448229375
  27.71516125689249]
 ['San Diego' '2024-05-11 09:30:59' 38.82017526915946 4.607511377146035
  28.732951288236187]
 ...
 ['San Jose' '2024-03-14 18:09:08' 81.31372480473425 2.161627975805372
  4.538363818725676]
 ['San Diego' '2024-02-08 21:12:09' 36.20267562952184 3.749677285096752
  9.298500900336268]
 ['New York' '2024-04-14 20:46:30' 80.68813773360876 8.539702382693964
  29.0]]

ENCODING DATA BY COLUMN TRANSFER

In [11]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [12]:
print(X)

[[0.0 0.0 0.0 ... 41.19575356694448 4.02011871570867 8.233540246873023]
 [0.0 0.0 0.0 ... 58.31910739552024 9.111623448229375 27.71516125689249]
 [0.0 0.0 0.0 ... 38.82017526915946 4.607511377146035 28.732951288236187]
 ...
 [0.0 0.0 0.0 ... 81.31372480473425 2.161627975805372 4.538363818725676]
 [0.0 0.0 0.0 ... 36.20267562952184 3.749677285096752 9.298500900336268]
 [0.0 0.0 0.0 ... 80.68813773360876 8.539702382693964 29.0]]

SPLITTING THE DATASET INTO TRAINING AND TEST SET

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [14]:
print(X_test)

[[0.0 0.0 0.0 ... 74.03043327506225 7.654251906839395 25.15890255768672]
 [0.0 0.0 0.0 ... 81.57816628773875 5.916095029224058 7.855950721010415]
 [0.0 0.0 0.0 ... 40.51751813735167 5.072308095008562 28.497890021057177]
 ...
 [0.0 0.0 0.0 ... 68.06458578082547 1.6104197698161415 0.9572925010537126]
 [0.0 0.0 0.0 ... 89.3210276712588 7.951855631969789 22.34456145829535]
 [0.0 0.0 0.0 ... 60.13642270500536 1.652693489981204 14.989635911231964]]

In [15]:
print(y_train)

[ 3.24079106  1.80054884 -2.13205652 ... 20.07220457  8.0336265
 24.72306895]

In [16]:
print(y_test)

[ 5.8469547   9.12599008 28.33410977 ... 39.14911406 11.81881546
 36.70936943]

STANDARDIZATION

In [17]:
from sklearn.preprocessing import StandardScaler
sta = StandardScaler()
X_train[:, 11:] = sta.fit_transform(X_train[:, 11:])
X_test[:, 11:] = sta.transform(X_test[:, 11:])

In [18]:
print(X_train[:, 11:])

[[0.647484071773482 0.5662078836102431 1.4755349321309816]
 [-1.719472407184635 -0.6757565824760208 0.13401798133406356]
 [-0.42447166143839804 -1.3447901786044767 -0.6324951818920916]
 ...
 [1.1604110524697975 0.8058856657292431 0.373644669271261]
 [-0.770922334686602 -0.8893041269145011 -1.321381762696124]
 [1.0697430230972098 0.09910938392104321 -1.1621224584253993]]

In [19]:
print(X_test[:, 11:])

[[0.8191295284934241 0.851315207507018 1.15396508167857]
 [1.2545424245661094 0.2637660388068904 -0.8121274523360752]
 [-1.1141602966025812 -0.021459258255196408 1.5333661448535902]
 ...
 [0.4749722920582056 -1.1916813675449338 -1.5960052871125607]
 [1.7012118673280114 0.9519141946032338 0.8341783148937637]
 [0.01761318309374587 -1.1773915819331078 -0.0015440718300837257]]

In [21]:

X_df = pd.DataFrame(X)
print("Cleansed Features (X) Head:")
display(X_df.head())

y_df = pd.DataFrame(y, columns=['target_variable'])
print("\nCleansed Target (y) Head:")
display(y_df.head())

Cleansed Features (X) Head:

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2024-01-14 21:12:46,41.195754,4.020119,8.23354
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2024-05-17 15:22:10,58.319107,9.111623,27.715161
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2024-05-11 09:30:59,38.820175,4.607511,28.732951
3,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,2024-02-26 17:32:39,54.074474,3.18372,26.367303
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2024-04-29 13:23:51,72.899908,9.598282,29.898622

Cleansed Target (y) Head:

   target_variable
0        10.683001
1         8.734140
2        11.632436
3        -8.628976
4        39.808213

In [22]:
X_df.to_csv('cleansed_features.csv', index=False)

y_df.to_csv('cleansed_target.csv', index=False)

Cleansed features saved to 'cleansed_features.csv'
Cleansed target saved to 'cleansed_target.csv'

In [25]:


original_X_columns = ['Location', 'Date_Time', 'Humidity_pct', 'Precipitation_mm', 'Wind_Speed_kmh']

all_feature_names = ct.get_feature_names_out(input_features=original_X_columns)

X_df = pd.DataFrame(X, columns=all_feature_names)

y_df = pd.DataFrame(y, columns=['target_variable'])

print("Cleansed Features (X) with proper column names:")
display(X_df.head())

print("\nCleansed Target (y) with proper column name:")
display(y_df.head())

X_df.to_csv('cleansed_features.csv', index=False)
y_df.to_csv('cleansed_target.csv', index=False)

Cleansed Features (X) with proper column names:

,encoder__Location_Chicago,encoder__Location_Dallas,encoder__Location_Houston,encoder__Location_Los Angeles,encoder__Location_New York,encoder__Location_Philadelphia,encoder__Location_Phoenix,encoder__Location_San Antonio,encoder__Location_San Diego,encoder__Location_San Jose,remainder__Date_Time,remainder__Humidity_pct,remainder__Precipitation_mm,remainder__Wind_Speed_kmh
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2024-01-14 21:12:46,41.195754,4.020119,8.23354
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2024-05-17 15:22:10,58.319107,9.111623,27.715161
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2024-05-11 09:30:59,38.820175,4.607511,28.732951
3,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,2024-02-26 17:32:39,54.074474,3.18372,26.367303
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2024-04-29 13:23:51,72.899908,9.598282,29.898622

Cleansed Target (y) with proper column name:

   target_variable
0        10.683001
1         8.734140
2        11.632436
3        -8.628976
4        39.808213