<a href="https://colab.research.google.com/github/DhruvMazumdar1110/Weather-Data-Preprocessing/blob/main/Weather_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

IMPORTING THE LIBRARIES

In [25]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from google.colab import drive

IMPORTING THE DATASET

In [26]:

drive.mount('/content/drive')
path = '/content/drive/MyDrive/Task_6/weather_data.csv'
dataset = pd.read_csv(path)

X= dataset.iloc[: , [0,1,3,4,5] ].values
y= dataset.iloc[: , 2].values

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [27]:
print(X)

[['San Diego' '2024-01-14 21:12:46' 41.19575356694448 4.02011871570867
  8.233540246873023]
 ['San Diego' '2024-05-17 15:22:10' 58.31910739552024 9.111623448229375
  27.71516125689249]
 ['San Diego' '2024-05-11 09:30:59' 38.82017526915946 4.607511377146035
  28.732951288236187]
 ...
 ['New York' '2024-04-14 08:30:09' 62.20188442965286 3.9875580386419296
  0.4039090307166959]
 ['Chicago' '2024-05-12 20:10:43' 63.7032451997448 4.294324709830695
  6.326035560339499]
 ['New York' '2024-04-16 16:11:52' 43.80458378329061 1.8832923531385992
  15.363828427249876]]

In [28]:
print(y)

[10.68300109  8.73413978 11.63243631 ... 15.66446487 18.99999414
 10.72535108]

HANDLING MISSING DATA

In [29]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 2:])
X[:, 2:] = imputer.transform(X[:, 2:])
print(X)

[['San Diego' '2024-01-14 21:12:46' 41.19575356694448 4.02011871570867
  8.233540246873023]
 ['San Diego' '2024-05-17 15:22:10' 58.31910739552024 9.111623448229375
  27.71516125689249]
 ['San Diego' '2024-05-11 09:30:59' 38.82017526915946 4.607511377146035
  28.732951288236187]
 ...
 ['New York' '2024-04-14 08:30:09' 62.20188442965286 3.9875580386419296
  0.4039090307166959]
 ['Chicago' '2024-05-12 20:10:43' 63.7032451997448 4.294324709830695
  6.326035560339499]
 ['New York' '2024-04-16 16:11:52' 43.80458378329061 1.8832923531385992
  15.363828427249876]]

ENCODING DATA BY COLUMN TRANSFER

In [30]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [31]:
print(X)

[[0.0 0.0 0.0 ... 41.19575356694448 4.02011871570867 8.233540246873023]
 [0.0 0.0 0.0 ... 58.31910739552024 9.111623448229375 27.71516125689249]
 [0.0 0.0 0.0 ... 38.82017526915946 4.607511377146035 28.732951288236187]
 ...
 [0.0 0.0 0.0 ... 62.20188442965286 3.9875580386419296 0.4039090307166959]
 [1.0 0.0 0.0 ... 63.7032451997448 4.294324709830695 6.326035560339499]
 [0.0 0.0 0.0 ... 43.80458378329061 1.8832923531385992 15.363828427249876]]

SPLITTING THE DATASET INTO TRAINING AND TEST SET

In [32]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [33]:
print(X_test)

[[1.0 0.0 0.0 ... 37.93230549581252 6.110468383563461 1.251755636729217]
 [0.0 0.0 0.0 ... 39.45551140514186 0.5111550671369725 29.184609387815208]
 [0.0 0.0 0.0 ... 44.65824742408648 1.829484479933028 25.065437226962597]
 ...
 [0.0 0.0 0.0 ... 85.81451582140424 4.225593787286509 3.972653028828072]
 [0.0 0.0 0.0 ... 57.69959580294685 2.031724211317626 8.980153539286022]
 [0.0 0.0 0.0 ... 60.04325064353535 2.162369283126715 20.94372271454007]]

In [34]:
print(y_train)

[33.94163963  6.18000445 34.97853983 ... 10.47014347 25.57357099
 24.22000906]

In [35]:
print(y_test)

[33.94970111 33.4490377   4.63809316 ... 37.23948546 20.88551904
 -2.41527116]

STANDARDIZATION

In [36]:
from sklearn.preprocessing import StandardScaler
sta = StandardScaler()
X_train[:, 11:] = sta.fit_transform(X_train[:, 11:])
X_test[:, 11:] = sta.transform(X_test[:, 11:])

In [37]:
print(X_train[:, 11:])

[[-0.5363951249224121 -0.5568414236755855 -1.571426356578452]
 [-0.6197285142935234 -0.5644665962529034 0.5928121585231124]
 [-1.008269251525935 1.1795386724268235 0.9899023576860284]
 ...
 [0.20965044431368485 -1.4511557470895553 0.004608869747621836]
 [0.8771653619931201 0.6827520519782618 0.44902377398636245]
 [-1.328111855882055 0.0003065379840683544 0.8891593459377976]]

In [38]:
print(X_test[:, 11:])

[[-1.275477718244021 0.33878204079306967 -1.586746844496884]
 [-1.1875367122552845 -1.5606492261391973 1.6380129086493007]
 [-0.8871611447778228 -1.1134379405275896 1.1624674910930561]
 ...
 [1.4889612320032224 -0.3006159603710574 -1.2726278332182863]
 [-0.13422991672637788 -1.0448330156913692 -0.694527713055807]
 [0.0010790149875691741 -1.0005148430438764 0.686628567076853]]

In [39]:

X_df = pd.DataFrame(X)
print("Cleansed Features (X) Head:")
display(X_df.head())

y_df = pd.DataFrame(y, columns=['target_variable'])
print("\nCleansed Target (y) Head:")
display(y_df.head())

Cleansed Features (X) Head:

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2024-01-14 21:12:46,41.195754,4.020119,8.23354
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2024-05-17 15:22:10,58.319107,9.111623,27.715161
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2024-05-11 09:30:59,38.820175,4.607511,28.732951
3,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,2024-02-26 17:32:39,54.074474,3.18372,26.367303
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2024-04-29 13:23:51,72.899908,9.598282,29.898622

Cleansed Target (y) Head:

   target_variable
0        10.683001
1         8.734140
2        11.632436
3        -8.628976
4        39.808213

In [40]:
X_df.to_csv('cleansed_features.csv', index=False)

y_df.to_csv('cleansed_target.csv', index=False)

In [41]:


original_X_columns = ['Location', 'Date_Time', 'Humidity_pct', 'Precipitation_mm', 'Wind_Speed_kmh']

all_feature_names = ct.get_feature_names_out(input_features=original_X_columns)

X_df = pd.DataFrame(X, columns=all_feature_names)

y_df = pd.DataFrame(y, columns=['target_variable'])

print("Cleansed Features (X) with proper column names:")
display(X_df.head())

print("\nCleansed Target (y) with proper column name:")
display(y_df.head())

X_df.to_csv('cleansed_features.csv', index=False)
y_df.to_csv('cleansed_target.csv', index=False)

Cleansed Features (X) with proper column names:

,encoder__Location_Chicago,encoder__Location_Dallas,encoder__Location_Houston,encoder__Location_Los Angeles,encoder__Location_New York,encoder__Location_Philadelphia,encoder__Location_Phoenix,encoder__Location_San Antonio,encoder__Location_San Diego,encoder__Location_San Jose,remainder__Date_Time,remainder__Humidity_pct,remainder__Precipitation_mm,remainder__Wind_Speed_kmh
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2024-01-14 21:12:46,41.195754,4.020119,8.23354
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2024-05-17 15:22:10,58.319107,9.111623,27.715161
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2024-05-11 09:30:59,38.820175,4.607511,28.732951
3,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,2024-02-26 17:32:39,54.074474,3.18372,26.367303
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2024-04-29 13:23:51,72.899908,9.598282,29.898622

Cleansed Target (y) with proper column name:

   target_variable
0        10.683001
1         8.734140
2        11.632436
3        -8.628976
4        39.808213